name: Enforce-CRLF
description: 'Enforce CRLF.'
branding:
  icon: "corner-down-left"
  color: "blue"
inputs:
  extensions:
    description: 'List of extensions (including the dot) seperated by a comma.'
    required: true
runs:
  using: "composite"
  # runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  - name: Set up Python 3.10
    uses: actions/setup-python@v5
    with:
      python-version: "3.10"
  - name: Install other dependencies
    run: |
      # REF: https://gist.github.com/sixman9/4082576
      # Install unix2dos and dos2unix on Ubuntu Linux
      # unix2dos and dos2unix are replace with todos and fromdos
      # We'll install those and then alias them
      sudo apt-get install tofrodos
      sudo ln -s /usr/bin/fromdos /usr/bin/dos2unix
      sudo ln -s /usr/bin/todos /usr/bin/unix2dos
      # TODO: Use Cache for APT: https://github.com/marketplace/actions/cache-apt-packages
    shell: bash
  - name: Run script
    run: |
      echo "${{ inputs.extensions }}"
      python '${{ github.action_path }}/enforce-crlf.py'
    shell: bash
  - name: Push content
    run: |
      git config user.name github-actions
      git config user.email github-actions@github.com

      # Add .bas files if they exist
      git add *.bas || true

      # Add .cls files if they exist
      git add *.cls || true

      # Add .frm files if they exist
      git add *.frm || true
      git status
      if [ -n "$(git diff --cached --exit-code)" ]; then
        echo "Changes detected"
        git commit -m "Enforce CRLF"
        git push --set-upstream origin $branch_name
      else
        echo "No changes to commit"
      fi
    shell: bash
