name: Enforce-CRLF
description: 'Enforce CRLF.'
branding:
  icon: "corner-down-left"
  color: "blue"
inputs:
  extensions:
    description: 'List of extensions (including the dot) seperated by a comma.'
    required: true
  bot-name:
    description: 'Name of the bot that will perform the commit.'
    default: 'github-actions'
  bot-email:
    description: 'Email of the bot that will perform the commit.'
    default: 'github-actions@github.com'
runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/checkout@v4
  - name: Set up Python 3.10
    uses: actions/setup-python@v5
    with:
      python-version: "3.10"
  - name: Get tofrodos package
    uses: awalsh128/cache-apt-pkgs-action@latest
    with:
      packages: tofrodos
      version: 1.0
  - name: Run script
    run: |
      python '${{ github.action_path }}/enforce-crlf.py' "${{ inputs.extensions }}"
    shell: bash
    - name: Push content
      uses: stefanzweifel/git-auto-commit-action@v5

  # - name: Push content
  #   run: |
  #     git config user.name "${{ inputs.bot-name }}"
  #     git config user.email "${{ inputs.bot-email }}"
      
  #     # Create an array of extensions
  #     IFS=',' read -r -a extensions <<< "${{ inputs.extensions }}"
      
  #     # Add files with the specified extensions
  #     for ext in "${extensions[@]}"; do
  #       trimmed_ext=$(echo "$ext" | xargs)  # Trim spaces
  #       echo "Adding files with extension: *$trimmed_ext"
  #       git add -v *"$trimmed_ext" || true
  #     done
      
  #     git status
  #     if [ -n "$(git diff --cached --exit-code)" ]; then
  #       echo "Changes detected"
  #       commit_message=$(printf "Enforce CRLF\n\nGitHub Action: %s/%s/actions/runs/%s" "${{ github.server_url }}" "${{ github.repository }}" "${{ github.run_id }}")
  #       git commit -m "$commit_message"        
  #       git push --set-upstream origin $branch_name
  #     else
  #       echo "No changes to commit"
  #     fi
  #   shell: bash
