name: Update Tags

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Update Tags
        uses: cssnr/update-version-tags-action@f3849a957cc45bae43abd0b41566ab269ec4fe02 # v2.1.0
        with:
          major: true
          minor: false